"""added updated_at column to assets

Revision ID: 1757fd6dd1c0
Revises: cb85c5c5aa41
Create Date: 2026-01-23 14:38:02.431636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1757fd6dd1c0'
down_revision: Union[str, Sequence[str], None] = 'cb85c5c5aa41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('assets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'updated_at')
    op.drop_column('assets', 'created_at')
    # ### end Alembic commands ###
